// favorate images
export const GET_FAV_IMAGES_START = "GET_FAV_IMAGES_START";
export const GET_FAV_IMAGES_SUCCESS = "GET_FAV_IMAGES_SUCCESS";
export const GET_FAV_IMAGES_ERROR = "GET_FAV_IMAGES_ERROR";

// category images
// export const GET_CAT_IMAGES_START = "GET_CAT_IMAGES_START";
// export const GET_CAT_IMAGES_SUCCESS = "GET_CAT_IMAGES_SUCCESS";
// export const GET_CAT_IMAGES_ERROR = "GET_CAT_IMAGES_ERROR";

// product images
export const GET_PRO_IMAGES_START = "GET_PRO_IMAGES_START";
export const GET_PRO_IMAGES_SUCCESS = "GET_PRO_IMAGES_SUCCESS";
export const GET_PRO_IMAGES_ERROR = "GET_PRO_IMAGES_ERROR";

export const GET_JEW_IMAGES_START = "GET_JEW_IMAGES_START";
export const GET_JEW_IMAGES_SUCCESS = "GET_JEW_IMAGES_SUCCESS";
export const GET_JEW_IMAGES_ERROR = "GET_JEW_IMAGES_ERROR";

export const SET_ACTIVE_ITEM ="SET_ACTIVE_ITEM";

export const GET_USER_DATA = "GET_USER_DATA";
export const POST_USER_DATA = "POST_USER_DATA";

export const SELECTED_CATEGORY = "SELECTED_CATEGORY";